### PR TITLE
Extend the `pkgConfig` and `json`(user config) objects

### PR DESCRIPTION
**Pull request by zerekw**
and then omit keys present in the blacklist

### CODE REVIEW

**Comment by aversini** [comment]
I'm not sure what you're trying to solve here?

## Here is what's happening before your code change
### Scenario 1
Key (private or not) is not in `.fedtoolsrc` but is present in `package.json`
In that case, line 206 will set that `keys` variable to an object with that missing key. Then the call to `this.setKey(keys)` will update the `.fedtoolsrc` file with that one key.
### Scenario 2
Key (private or not) is in `.fedtoolsrc` and also present in `package.json`
In that case, line 206 will set that `keys` variable to an empty object since there is no need to update the config file.

## Here is what's happening after your code change:
### Scenario 1
Key (private or not) is not in `.fedtoolsrc` but is present in `package.json`
In that case, line 206 will set that `keys` variable to an object with ALL the keys, including the missing key.
### Scenario 2
Key (private or not) is in `.fedtoolsrc` and also present in `package.json`
In that case, line 206 will set that `keys` variable to an object with ALL the keys.

**Comment by zerekw** [comment]
The `.fedtoolsrc` file was not using the updated `wria2yui3giturl` value I had given it. This fixed it for me. I agree with what you are saying. This isn't the right way to go about it. Let me take another swing at it

**Comment by zerekw** [comment]
Fixed it. All I needed was the `_.extend` to happen on the config object that was passed in. This combines the default `packge.json` and the `.fedtoolsrc`.

**Comment by aversini** [comment]
Not working for me, your change has nothing to do with the problem. The issue is in fedtools at that line https://github.com/aversini/fedtools/blob/master/lib/wria2-package.js#L298
This line is always reading the package.json and never takes the custom configuration into account.

**Comment by aversini** [comment]
Sorry @zerekw couldn't help myself: your issue is resolved by fedtools v1.0.63

**Comment by zerekw** [comment]
Weird. I was able to get my build working with that change. With the change I had made it should have been making one object with all the key/values from both `pkgConfig` and the `.fedtoolsrc`. The other thought I had was to just return the an object that `config` could be set to at the init call. https://github.com/aversini/fedtools/blob/master/lib/cli/cli.js#L45

The use case I am considering with combining both the default `pkgConfig` with the `.fedtoolsrc` is then fedtools can always use its own config property that should have all the key/values it needs.

**Comment by aversini** [comment]
Strange indeed since this configuration was not read at all by the war builder part to create a shallow clone of YUI.
Are you sure it was really working or maybe you did modify the package.json manually to test, and forgot to reset it?

With your last change, the object was exactly the same as with the original code. With your previous (first change), yes, in that case the object had all the key/values from both files, but that was overkill since it was updating the .fedtoolsrc file all the time. 

I’m not sure I understand the use case, can you give me an example?

**Comment by zerekw** [comment]
The result I thought I was seeing was something along the lines of the following:

```javascript
var pkgConfig = {
  defaultbranch: 'wf2-develop',
  wria2yui3giturl: 'wf2github.url'
};

var fedtoolsrcConfig = {
  wria2yui3giturl: 'mycustomgithub.org'
}

_.extend(pkgConfig, fedtoolsrcConfig);

pkgConfig // => { defaultbranch: 'wf2-develop', wria2yui3giturl: 'mycustomgithub.org' }
```

When I tried running the `war` command without my change it was never able to find my branch since it was not looking at the correct url.

**Pull request closed without merging**
